version: '2'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
     - node
    links:
     - node:react-server-docs
    ports:
     - "8080:80"
    volumes_from:
     - node:ro
