var fs = require('fs'),
	rimraf = require("rimraf"),
	bundleNameUtil = require('../core/util/bundleNameUtil');

function cleanTargetDir() {
	var targetDirName = "./target-entrypoints";
	//TODO better error handling etc.
	if (fs.existsSync(targetDirName)) {
		var stats = fs.statSync(targetDirName);
		if (stats.isDirectory) {
			rimraf.sync(targetDirName);
		} else if (stats.isFile) {
			fs.unlinkSync(targetDirName);
		}		
	} 
	fs.mkdirSync(targetDirName);
}

module.exports = function(routesFilename) {
	var routes = fs.readFileSync(routesFilename, {encoding: "utf8"});
	routes = 
		"var module={};\n" +
		"function require(){return null;};\n" +
	 	"function __LAZY_REQUIRE__(arg){return arg;};\n" + 
	 	routes + "\n" +
	 	"return module.exports;";

	routes = new Function(routes)();
	var routeNames = Object.keys(routes);
	
	cleanTargetDir();

	var entryPoints = {};

	for (var i=0; i < routeNames.length; i++) {		
	 	var routeName = routeNames[i];	 	
	 	if (!routes[routeName].resolveComponent) {
	 		console.error("route " + routeName + " has no resolveComponent property");
	 	}

	 	var entryPointCode = 
	 		"// file generated by EntryPointGenerator.js\n" +
	 		"var client = require('../client');\n" +
	 		"var routes = require('../routes/routes')\n" +
			"window.rfBootstrap = function () {\n" +
			// make sure component is part of the entrypoint
			"\tvar component = require('" + routes[routeName].resolveComponent + "');\n" +
			"\tvar renderDfd = client.initialize(component, routes);\n" +
			"\twindow.__lateArrival = function __lateArrival (url, data) {\n" +
			"\t\trenderDfd.done(function () {\n" +
			"\t\t\tvar context = window.controller.context;\n" +
			"\t\t\tcontext.loader.lateArrival(url, data);\n" +
			"\t\t});\n" +
			"\t}\n" +
			"\treturn renderDfd;\n" +
			"}";

		var outFileName = "./target-entrypoints/" + routeName + "Entry__generated.js";

	 	fs.writeFileSync(outFileName, entryPointCode);

	 	entryPoints[bundleNameUtil.getEntryPointNameFromRouteName(routeName)] = outFileName;
	 }	 

	 return entryPoints;
}


